# Generated by Django 6.0.7 on 2026-07-19 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('full_name', models.CharField(help_text='Full name displayed on the portfolio.', max_length=200)),
                ('professional_title', models.CharField(help_text='Professional title or headline (e.g., Full Stack Developer).', max_length=200)),
                ('about', models.TextField(help_text='Detailed about/bio section.')),
                ('email', models.EmailField(help_text='Contact email address.', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional).', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Physical address or location (optional).', max_length=300)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL.', max_length=300)),
                ('github', models.URLField(blank=True, help_text='GitHub profile URL.', max_length=300)),
                ('resume', models.FileField(blank=True, help_text='Resume/CV file upload (PDF preferred).', null=True, upload_to='resumes/')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile photo displayed across the portfolio.', null=True, upload_to='profile/')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image.', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Website Information',
                'verbose_name_plural': 'Website Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
