# Generated by Django 6.0.7 on 2026-07-19 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(help_text='Project title.', max_length=200)),
                ('description', models.TextField(help_text='Detailed project description.')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies used.', max_length=500)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL.', max_length=300)),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL.', max_length=300)),
                ('project_image', models.ImageField(blank=True, help_text='Project screenshot or thumbnail image.', null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False, help_text='Whether this project should be featured/highlighted.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
