export const siteConfig = {
  name: 'MOHAMMED FAVAS KS',
  title: 'Fullstack Web Developer',
  tagline: 'Crafting digital experiences with code & creativity',
  email: 'fv8favas@gmail.com',
  phone: '+91 7736316028',
  location: 'Thrissur, Kerala, India',
  available: true,
  resumeUrl: '/ai_portfolio/resume.pdf',
  github: 'https://github.com/favas-fv8',
  linkedin: 'https://www.linkedin.com/in/favasfv8',
  twitter: 'https://x.com/8Favas34427',
  instagram: 'https://www.instagram.com/favas_8_/',
  repo: 'ai_portfolio',
  url: 'https://favas-fv8.github.io/ai_portfolio',
} as const
